import { BootcampVocabWord } from '@/types';

/**
 * Hebrew Reading Bootcamp — Vocabulary Module
 * 50+ essential Jewish words organized by category.
 * All original content — cultural notes connect each word to Jewish life.
 *
 * Each word references the letter/vowel IDs it uses,
 * so the app knows which skills are being practiced.
 */

export const BOOTCAMP_VOCAB: BootcampVocabWord[] = [
  // ==========================================
  // GREETINGS & DAILY EXPRESSIONS
  // ==========================================
  {
    id: 'vocab_shalom',
    hebrew: 'שָׁלוֹם',
    transliteration: 'shalom',
    translation: 'peace / hello / goodbye',
    category: 'greetings',
    audioUrl: '/audio/bootcamp/words/shalom.mp3',
    letterIds: ['shin', 'lamed', 'vav', 'mem_sofit'],
    vowelIds: ['kamatz', 'cholam_vav'],
    dayIntroduced: 1,
    difficulty: 1,
    culturalNote: 'The most universal Hebrew word. From the root meaning "wholeness" — every greeting is a prayer for completeness.',
  },
  {
    id: 'vocab_todah',
    hebrew: 'תּוֹדָה',
    transliteration: 'todah',
    translation: 'thank you',
    category: 'greetings',
    audioUrl: '/audio/bootcamp/words/todah.mp3',
    letterIds: ['tav', 'vav', 'dalet', 'hei'],
    vowelIds: ['cholam_vav', 'kamatz'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'Gratitude is central to Jewish life. The morning prayer Modeh Ani begins with thanks.',
  },
  {
    id: 'vocab_boker_tov',
    hebrew: 'בֹּקֶר טוֹב',
    transliteration: 'boker tov',
    translation: 'good morning',
    category: 'greetings',
    audioUrl: '/audio/bootcamp/words/boker_tov.mp3',
    letterIds: ['bet', 'kuf', 'resh', 'tet', 'vav', 'vet'],
    vowelIds: ['cholam', 'segol', 'cholam_vav'],
    dayIntroduced: 4,
    difficulty: 2,
  },
  {
    id: 'vocab_mazel_tov',
    hebrew: 'מַזָּל טוֹב',
    transliteration: 'mazal tov',
    translation: 'congratulations / good fortune',
    category: 'greetings',
    audioUrl: '/audio/bootcamp/words/mazel_tov.mp3',
    letterIds: ['mem', 'zayin', 'lamed', 'tet', 'vav', 'vet'],
    vowelIds: ['patach', 'kamatz', 'cholam_vav'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'Literally "good constellation." Said at weddings, bar mitzvahs, and any joyous occasion.',
  },
  {
    id: 'vocab_bevakasha',
    hebrew: 'בְּבַקָּשָׁה',
    transliteration: "b'vakasha",
    translation: 'please / you are welcome',
    category: 'greetings',
    audioUrl: '/audio/bootcamp/words/bevakasha.mp3',
    letterIds: ['bet', 'vet', 'kuf', 'shin', 'hei'],
    vowelIds: ['shva', 'patach', 'kamatz'],
    dayIntroduced: 4,
    difficulty: 3,
  },
  {
    id: 'vocab_lechayim',
    hebrew: 'לְחַיִּים',
    transliteration: "l'chayim",
    translation: 'to life! (a toast)',
    category: 'greetings',
    audioUrl: '/audio/bootcamp/words/lechayim.mp3',
    letterIds: ['lamed', 'chet', 'yud', 'mem_sofit'],
    vowelIds: ['shva', 'patach', 'chirik'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'The quintessential Jewish toast. Judaism celebrates life above all else.',
  },

  // ==========================================
  // BRACHOT (BLESSINGS)
  // ==========================================
  {
    id: 'vocab_baruch',
    hebrew: 'בָּרוּךְ',
    transliteration: 'baruch',
    translation: 'blessed',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/baruch.mp3',
    letterIds: ['bet', 'resh', 'vav', 'chaf_sofit'],
    vowelIds: ['kamatz', 'shuruk', 'shva'],
    dayIntroduced: 2,
    difficulty: 2,
    culturalNote: 'The first word of nearly every bracha. From the root meaning "knee" — we bend in acknowledgment.',
  },
  {
    id: 'vocab_atah',
    hebrew: 'אַתָּה',
    transliteration: 'atah',
    translation: 'You (addressing G-d)',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/atah.mp3',
    letterIds: ['aleph', 'tav', 'hei'],
    vowelIds: ['patach', 'kamatz'],
    dayIntroduced: 1,
    difficulty: 1,
    culturalNote: 'We speak to G-d in second person — directly and personally, like a conversation.',
  },
  {
    id: 'vocab_melech',
    hebrew: 'מֶלֶךְ',
    transliteration: 'melech',
    translation: 'king',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/melech.mp3',
    letterIds: ['mem', 'lamed', 'chaf_sofit'],
    vowelIds: ['segol', 'segol', 'shva'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'G-d is called "King of the universe" in every bracha — sovereignty over all creation.',
  },
  {
    id: 'vocab_haolam',
    hebrew: 'הָעוֹלָם',
    transliteration: "ha'olam",
    translation: 'the world / the universe',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/haolam.mp3',
    letterIds: ['hei', 'ayin', 'vav', 'lamed', 'mem_sofit'],
    vowelIds: ['kamatz', 'cholam_vav', 'kamatz'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'Olam means both "world" and "eternity." Every bracha acknowledges G-d as master of time and space.',
  },
  {
    id: 'vocab_amen',
    hebrew: 'אָמֵן',
    transliteration: 'amen',
    translation: 'so be it / I believe',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/amen.mp3',
    letterIds: ['aleph', 'mem', 'nun_sofit'],
    vowelIds: ['kamatz', 'tzere'],
    dayIntroduced: 2,
    difficulty: 1,
    culturalNote: 'From the root for "faith" and "truth." Saying amen affirms another person\'s blessing.',
  },
  {
    id: 'vocab_borei',
    hebrew: 'בּוֹרֵא',
    transliteration: 'borei',
    translation: 'who creates',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/borei.mp3',
    letterIds: ['bet', 'vav', 'resh', 'aleph'],
    vowelIds: ['cholam_vav', 'tzere'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'Blessings over food thank G-d as "Creator." Every bite is a moment of gratitude.',
  },
  {
    id: 'vocab_lechem',
    hebrew: 'לֶחֶם',
    transliteration: 'lechem',
    translation: 'bread',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/lechem.mp3',
    letterIds: ['lamed', 'chet', 'mem_sofit'],
    vowelIds: ['segol', 'segol'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'Bread is the staple food in Jewish law. Hamotzi is the blessing said before eating bread.',
  },
  {
    id: 'vocab_pri',
    hebrew: 'פְּרִי',
    transliteration: 'pri',
    translation: 'fruit',
    category: 'brachot',
    audioUrl: '/audio/bootcamp/words/pri.mp3',
    letterIds: ['pei', 'resh', 'yud'],
    vowelIds: ['shva', 'chirik'],
    dayIntroduced: 4,
    difficulty: 2,
  },

  // ==========================================
  // SHABBAT
  // ==========================================
  {
    id: 'vocab_shabbat',
    hebrew: 'שַׁבָּת',
    transliteration: 'shabbat',
    translation: 'Sabbath / day of rest',
    category: 'shabbat',
    audioUrl: '/audio/bootcamp/words/shabbat.mp3',
    letterIds: ['shin', 'bet', 'tav'],
    vowelIds: ['patach', 'kamatz'],
    dayIntroduced: 2,
    difficulty: 1,
    culturalNote: 'The weekly day of rest, from Friday sunset to Saturday night. The crown jewel of the Jewish week.',
  },
  {
    id: 'vocab_kiddush',
    hebrew: 'קִדּוּשׁ',
    transliteration: 'kiddush',
    translation: 'sanctification (blessing over wine)',
    category: 'shabbat',
    audioUrl: '/audio/bootcamp/words/kiddush.mp3',
    letterIds: ['kuf', 'dalet', 'vav', 'shin'],
    vowelIds: ['chirik', 'shuruk'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'Friday night Kiddush sanctifies Shabbat over a cup of wine. It declares the day as holy.',
  },
  {
    id: 'vocab_challah',
    hebrew: 'חַלָּה',
    transliteration: 'challah',
    translation: 'braided bread for Shabbat',
    category: 'shabbat',
    audioUrl: '/audio/bootcamp/words/challah.mp3',
    letterIds: ['chet', 'lamed', 'hei'],
    vowelIds: ['patach', 'kamatz'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'Two challot are placed on the Shabbat table, recalling the double portion of manna in the desert.',
  },
  {
    id: 'vocab_ner',
    hebrew: 'נֵר',
    transliteration: 'ner',
    translation: 'candle / light',
    category: 'shabbat',
    audioUrl: '/audio/bootcamp/words/ner.mp3',
    letterIds: ['nun', 'resh'],
    vowelIds: ['tzere'],
    dayIntroduced: 2,
    difficulty: 1,
    culturalNote: 'Shabbat begins with lighting candles. The flame represents the extra soul we receive on Shabbat.',
  },
  {
    id: 'vocab_havdalah',
    hebrew: 'הַבְדָּלָה',
    transliteration: 'havdalah',
    translation: 'separation (end-of-Shabbat ceremony)',
    category: 'shabbat',
    audioUrl: '/audio/bootcamp/words/havdalah.mp3',
    letterIds: ['hei', 'vet', 'dalet', 'lamed', 'hei'],
    vowelIds: ['patach', 'shva', 'kamatz', 'kamatz'],
    dayIntroduced: 4,
    difficulty: 3,
    culturalNote: 'A multi-sensory ceremony with wine, spices, and a braided candle. We say goodbye to Shabbat with sweetness.',
  },
  {
    id: 'vocab_oneg',
    hebrew: 'עֹנֶג',
    transliteration: 'oneg',
    translation: 'delight / pleasure',
    category: 'shabbat',
    audioUrl: '/audio/bootcamp/words/oneg.mp3',
    letterIds: ['ayin', 'nun', 'gimel'],
    vowelIds: ['cholam', 'segol'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: '"Oneg Shabbat" is the joyful Shabbat gathering — delighting in rest, food, and community.',
  },

  // ==========================================
  // HOLIDAYS
  // ==========================================
  {
    id: 'vocab_pesach',
    hebrew: 'פֶּסַח',
    transliteration: 'pesach',
    translation: 'Passover',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/pesach.mp3',
    letterIds: ['pei', 'samech', 'chet'],
    vowelIds: ['segol', 'patach'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'Celebrates the Exodus from Egypt. "Pesach" means "passed over" — G-d passed over Jewish homes.',
  },
  {
    id: 'vocab_sukkah',
    hebrew: 'סוּכָּה',
    transliteration: 'sukkah',
    translation: 'temporary hut (for Sukkot)',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/sukkah.mp3',
    letterIds: ['samech', 'vav', 'kaf', 'hei'],
    vowelIds: ['shuruk', 'kamatz'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'We eat and sleep in temporary huts for a week, remembering our vulnerability and G-d\'s protection.',
  },
  {
    id: 'vocab_chanukah',
    hebrew: 'חֲנֻכָּה',
    transliteration: 'chanukah',
    translation: 'dedication (Festival of Lights)',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/chanukah.mp3',
    letterIds: ['chet', 'nun', 'vav', 'kaf', 'hei'],
    vowelIds: ['chataf_patach', 'kubutz', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 3,
    culturalNote: 'Means "dedication." Celebrates the rededication of the Temple and the miracle of the oil.',
  },
  {
    id: 'vocab_purim',
    hebrew: 'פּוּרִים',
    transliteration: 'purim',
    translation: 'lots (festive holiday)',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/purim.mp3',
    letterIds: ['pei', 'vav', 'resh', 'yud', 'mem_sofit'],
    vowelIds: ['shuruk', 'chirik'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'Named for the "lots" cast by Haman. A day of joy, costumes, and gifts to friends.',
  },
  {
    id: 'vocab_rosh_hashana',
    hebrew: 'רֹאשׁ הַשָּׁנָה',
    transliteration: 'rosh hashana',
    translation: 'head of the year (Jewish New Year)',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/rosh_hashana.mp3',
    letterIds: ['resh', 'aleph', 'shin', 'hei', 'shin', 'nun', 'hei'],
    vowelIds: ['cholam', 'patach', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 3,
    culturalNote: 'The birthday of the world. A time of reflection, teshuvah, and the shofar\'s call.',
  },
  {
    id: 'vocab_yom_kippur',
    hebrew: 'יוֹם כִּפּוּר',
    transliteration: 'yom kippur',
    translation: 'Day of Atonement',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/yom_kippur.mp3',
    letterIds: ['yud', 'vav', 'mem_sofit', 'kaf', 'pei', 'vav', 'resh'],
    vowelIds: ['cholam_vav', 'chirik', 'shuruk'],
    dayIntroduced: 5,
    difficulty: 3,
    culturalNote: 'The holiest day of the year. A 25-hour fast focused on repentance and spiritual renewal.',
  },
  {
    id: 'vocab_shavuot',
    hebrew: 'שָׁבוּעוֹת',
    transliteration: 'shavuot',
    translation: 'weeks (festival of Torah giving)',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/shavuot.mp3',
    letterIds: ['shin', 'vet', 'vav', 'ayin', 'vav', 'tav'],
    vowelIds: ['kamatz', 'shuruk', 'cholam_vav'],
    dayIntroduced: 5,
    difficulty: 3,
    culturalNote: 'Celebrates receiving the Torah at Sinai. Tradition: stay up all night learning.',
  },
  {
    id: 'vocab_simcha',
    hebrew: 'שִׂמְחָה',
    transliteration: 'simcha',
    translation: 'joy / celebration',
    category: 'holidays',
    audioUrl: '/audio/bootcamp/words/simcha.mp3',
    letterIds: ['sin', 'mem', 'chet', 'hei'],
    vowelIds: ['chirik', 'shva', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 2,
    culturalNote: 'Joy is a mitzvah in Judaism. Every holiday and lifecycle event is a simcha.',
  },

  // ==========================================
  // PRAYER
  // ==========================================
  {
    id: 'vocab_tefillah',
    hebrew: 'תְּפִלָּה',
    transliteration: 'tefillah',
    translation: 'prayer',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/tefillah.mp3',
    letterIds: ['tav', 'pei', 'lamed', 'hei'],
    vowelIds: ['shva', 'chirik', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 3,
    culturalNote: 'From the root meaning "to judge oneself." Prayer is self-reflection before G-d.',
  },
  {
    id: 'vocab_siddur',
    hebrew: 'סִדּוּר',
    transliteration: 'siddur',
    translation: 'prayer book',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/siddur.mp3',
    letterIds: ['samech', 'dalet', 'vav', 'resh'],
    vowelIds: ['chirik', 'shuruk'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'From the root "seder" (order). The siddur gives structure to our conversation with G-d.',
  },
  {
    id: 'vocab_shema',
    hebrew: 'שְׁמַע',
    transliteration: 'shma',
    translation: 'hear / listen',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/shema.mp3',
    letterIds: ['shin', 'mem', 'ayin'],
    vowelIds: ['shva', 'patach'],
    dayIntroduced: 4,
    difficulty: 1,
    culturalNote: 'The most important prayer in Judaism. "Hear, O Israel" — a declaration of G-d\'s oneness.',
  },
  {
    id: 'vocab_modeh',
    hebrew: 'מוֹדֶה',
    transliteration: 'modeh',
    translation: 'I give thanks',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/modeh.mp3',
    letterIds: ['mem', 'vav', 'dalet', 'hei'],
    vowelIds: ['cholam_vav', 'segol'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: 'The very first word a Jew says each morning. Before anything else — gratitude.',
  },
  {
    id: 'vocab_kadosh',
    hebrew: 'קָדוֹשׁ',
    transliteration: 'kadosh',
    translation: 'holy',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/kadosh.mp3',
    letterIds: ['kuf', 'dalet', 'vav', 'shin'],
    vowelIds: ['kamatz', 'cholam_vav'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'Holiness means "set apart." We say "Kadosh, Kadosh, Kadosh" — Holy, Holy, Holy.',
  },
  {
    id: 'vocab_halleluyah',
    hebrew: 'הַלְּלוּיָהּ',
    transliteration: 'halleluyah',
    translation: 'praise G-d',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/halleluyah.mp3',
    letterIds: ['hei', 'lamed', 'vav', 'yud', 'hei'],
    vowelIds: ['patach', 'shva', 'shuruk', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 3,
    culturalNote: 'From "hallel" (praise) + "Yah" (G-d\'s name). The universal expression of divine praise.',
  },
  {
    id: 'vocab_adonai',
    hebrew: 'אֲדֹנָי',
    transliteration: 'Adonai',
    translation: 'my Lord (name for G-d)',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/adonai.mp3',
    letterIds: ['aleph', 'dalet', 'nun', 'yud'],
    vowelIds: ['chataf_patach', 'cholam', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 2,
    culturalNote: 'The way we pronounce the four-letter Name of G-d during prayer.',
  },
  {
    id: 'vocab_echad',
    hebrew: 'אֶחָד',
    transliteration: 'echad',
    translation: 'one',
    category: 'prayer',
    audioUrl: '/audio/bootcamp/words/echad.mp3',
    letterIds: ['aleph', 'chet', 'dalet'],
    vowelIds: ['segol', 'kamatz'],
    dayIntroduced: 3,
    difficulty: 1,
    culturalNote: 'The last word of the Shema. "G-d is ONE" — the fundamental declaration of Jewish faith.',
  },

  // ==========================================
  // TORAH & VALUES
  // ==========================================
  {
    id: 'vocab_torah',
    hebrew: 'תּוֹרָה',
    transliteration: 'Torah',
    translation: 'Torah / teaching / instruction',
    category: 'torah',
    audioUrl: '/audio/bootcamp/words/torah.mp3',
    letterIds: ['tav', 'vav', 'resh', 'hei'],
    vowelIds: ['cholam_vav', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 2,
    culturalNote: 'From the root "to teach." The Torah is the five books of Moses — the foundation of Jewish life.',
  },
  {
    id: 'vocab_bereishit',
    hebrew: 'בְּרֵאשִׁית',
    transliteration: 'bereishit',
    translation: 'in the beginning',
    category: 'torah',
    audioUrl: '/audio/bootcamp/words/bereishit.mp3',
    letterIds: ['bet', 'resh', 'aleph', 'shin', 'yud', 'tav'],
    vowelIds: ['shva', 'tzere', 'chirik'],
    dayIntroduced: 5,
    difficulty: 4,
    culturalNote: 'The very first word of the Torah. The entire story of creation begins with this word.',
  },
  {
    id: 'vocab_mitzvah',
    hebrew: 'מִצְוָה',
    transliteration: 'mitzvah',
    translation: 'commandment / good deed',
    category: 'torah',
    audioUrl: '/audio/bootcamp/words/mitzvah.mp3',
    letterIds: ['mem', 'tzadi', 'vav', 'hei'],
    vowelIds: ['chirik', 'shva', 'kamatz'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'There are 613 mitzvot in the Torah. A mitzvah connects us to G-d through action.',
  },
  {
    id: 'vocab_chesed',
    hebrew: 'חֶסֶד',
    transliteration: 'chesed',
    translation: 'lovingkindness / grace',
    category: 'torah',
    audioUrl: '/audio/bootcamp/words/chesed.mp3',
    letterIds: ['chet', 'samech', 'dalet'],
    vowelIds: ['segol', 'segol'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'One of the highest Jewish values. Chesed means going beyond the letter of the law to be kind.',
  },
  {
    id: 'vocab_tzedek',
    hebrew: 'צֶדֶק',
    transliteration: 'tzedek',
    translation: 'justice / righteousness',
    category: 'torah',
    audioUrl: '/audio/bootcamp/words/tzedek.mp3',
    letterIds: ['tzadi', 'dalet', 'kuf'],
    vowelIds: ['segol', 'segol'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: '"Tzedek, tzedek tirdof" — "Justice, justice shall you pursue." Repeated for emphasis.',
  },
  {
    id: 'vocab_emet',
    hebrew: 'אֱמֶת',
    transliteration: 'emet',
    translation: 'truth',
    category: 'torah',
    audioUrl: '/audio/bootcamp/words/emet.mp3',
    letterIds: ['aleph', 'mem', 'tav'],
    vowelIds: ['chataf_segol', 'segol'],
    dayIntroduced: 1,
    difficulty: 1,
    culturalNote: 'Made of the first, middle, and last letters of the aleph-bet — truth spans everything.',
  },
  {
    id: 'vocab_derech',
    hebrew: 'דֶּרֶךְ',
    transliteration: 'derech',
    translation: 'way / path',
    category: 'torah',
    audioUrl: '/audio/bootcamp/words/derech.mp3',
    letterIds: ['dalet', 'resh', 'chaf_sofit'],
    vowelIds: ['segol', 'segol', 'shva'],
    dayIntroduced: 3,
    difficulty: 2,
    culturalNote: '"Derech eretz" — the way of the land — means basic human decency. It precedes Torah.',
  },

  // ==========================================
  // LIFECYCLE
  // ==========================================
  {
    id: 'vocab_brit',
    hebrew: 'בְּרִית',
    transliteration: 'brit',
    translation: 'covenant / circumcision',
    category: 'lifecycle',
    audioUrl: '/audio/bootcamp/words/brit.mp3',
    letterIds: ['bet', 'resh', 'yud', 'tav'],
    vowelIds: ['shva', 'chirik'],
    dayIntroduced: 5,
    difficulty: 2,
    culturalNote: 'The covenant between G-d and the Jewish people, signed on the body at 8 days old.',
  },
  {
    id: 'vocab_bar_mitzvah',
    hebrew: 'בַּר מִצְוָה',
    transliteration: 'bar mitzvah',
    translation: 'son of the commandment',
    category: 'lifecycle',
    audioUrl: '/audio/bootcamp/words/bar_mitzvah.mp3',
    letterIds: ['bet', 'resh', 'mem', 'tzadi', 'vav', 'hei'],
    vowelIds: ['patach', 'chirik', 'shva', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 3,
    culturalNote: 'At age 13, a Jewish boy becomes responsible for the mitzvot. A moment of spiritual coming of age.',
  },
  {
    id: 'vocab_chuppah',
    hebrew: 'חוּפָּה',
    transliteration: 'chuppah',
    translation: 'wedding canopy',
    category: 'lifecycle',
    audioUrl: '/audio/bootcamp/words/chuppah.mp3',
    letterIds: ['chet', 'vav', 'pei', 'hei'],
    vowelIds: ['shuruk', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 2,
    culturalNote: 'The open-sided canopy under which couples marry — open to welcome guests from all directions.',
  },
  {
    id: 'vocab_neshama',
    hebrew: 'נְשָׁמָה',
    transliteration: 'neshama',
    translation: 'soul',
    category: 'lifecycle',
    audioUrl: '/audio/bootcamp/words/neshama.mp3',
    letterIds: ['nun', 'shin', 'mem', 'hei'],
    vowelIds: ['shva', 'kamatz', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 2,
    culturalNote: 'Every morning we thank G-d for returning our neshama. Sleep is a mini-death; waking is rebirth.',
  },
  {
    id: 'vocab_chai',
    hebrew: 'חַי',
    transliteration: 'chai',
    translation: 'life / alive',
    category: 'lifecycle',
    audioUrl: '/audio/bootcamp/words/chai.mp3',
    letterIds: ['chet', 'yud'],
    vowelIds: ['patach'],
    dayIntroduced: 3,
    difficulty: 1,
    culturalNote: 'The numerical value of chai is 18. That\'s why Jews give gifts in multiples of 18.',
  },

  // ==========================================
  // DAILY LIFE
  // ==========================================
  {
    id: 'vocab_bayit',
    hebrew: 'בַּיִת',
    transliteration: 'bayit',
    translation: 'house / home',
    category: 'daily_life',
    audioUrl: '/audio/bootcamp/words/bayit.mp3',
    letterIds: ['bet', 'yud', 'tav'],
    vowelIds: ['patach', 'chirik'],
    dayIntroduced: 2,
    difficulty: 1,
    culturalNote: 'The letter Bet itself means "house." The Torah begins with Bet — the world is G-d\'s house.',
  },
  {
    id: 'vocab_sefer',
    hebrew: 'סֵפֶר',
    transliteration: 'sefer',
    translation: 'book',
    category: 'daily_life',
    audioUrl: '/audio/bootcamp/words/sefer.mp3',
    letterIds: ['samech', 'pei', 'resh'],
    vowelIds: ['tzere', 'segol'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: 'Jews are called "People of the Book." A sefer Torah is the holiest object in the synagogue.',
  },
  {
    id: 'vocab_mayim',
    hebrew: 'מַיִם',
    transliteration: 'mayim',
    translation: 'water',
    category: 'daily_life',
    audioUrl: '/audio/bootcamp/words/mayim.mp3',
    letterIds: ['mem', 'yud', 'mem_sofit'],
    vowelIds: ['patach', 'chirik'],
    dayIntroduced: 2,
    difficulty: 1,
    culturalNote: 'Torah is compared to water — it flows, sustains life, and seeks the lowest place.',
  },
  {
    id: 'vocab_eretz',
    hebrew: 'אֶרֶץ',
    transliteration: 'eretz',
    translation: 'land',
    category: 'daily_life',
    audioUrl: '/audio/bootcamp/words/eretz.mp3',
    letterIds: ['aleph', 'resh', 'tzadi_sofit'],
    vowelIds: ['segol', 'segol'],
    dayIntroduced: 4,
    difficulty: 2,
    culturalNote: '"Eretz Yisrael" — the Land of Israel — is central to Jewish identity and prayer.',
  },
  {
    id: 'vocab_yisrael',
    hebrew: 'יִשְׂרָאֵל',
    transliteration: 'yisrael',
    translation: 'Israel',
    category: 'daily_life',
    audioUrl: '/audio/bootcamp/words/yisrael.mp3',
    letterIds: ['yud', 'sin', 'resh', 'aleph', 'lamed'],
    vowelIds: ['chirik', 'shva', 'kamatz', 'tzere'],
    dayIntroduced: 4,
    difficulty: 3,
    culturalNote: 'The name given to Jacob after he wrestled with an angel. Means "one who struggles with G-d."',
  },
  {
    id: 'vocab_mezuzah',
    hebrew: 'מְזוּזָה',
    transliteration: 'mezuzah',
    translation: 'doorpost scroll',
    category: 'daily_life',
    audioUrl: '/audio/bootcamp/words/mezuzah.mp3',
    letterIds: ['mem', 'zayin', 'vav', 'zayin', 'hei'],
    vowelIds: ['shva', 'shuruk', 'kamatz'],
    dayIntroduced: 5,
    difficulty: 2,
    culturalNote: 'A small scroll on the doorpost containing the Shema. A reminder of G-d every time you enter or leave.',
  },
];

// Helpers
export function getBootcampVocabByCategory(category: BootcampVocabWord['category']): BootcampVocabWord[] {
  return BOOTCAMP_VOCAB.filter(w => w.category === category);
}

export function getBootcampVocabByDay(day: number): BootcampVocabWord[] {
  return BOOTCAMP_VOCAB.filter(w => w.dayIntroduced <= day);
}

export function getBootcampVocabById(id: string): BootcampVocabWord | undefined {
  return BOOTCAMP_VOCAB.find(w => w.id === id);
}
