import { Prayer } from '@/types';

/**
 * Prayers in the "Daven Path" order.
 * Each prayer includes context, meaning, and sections with Hebrew + transliteration + translation.
 */

export const PRAYERS: Prayer[] = [
  {
    id: 'modeh-ani',
    slug: 'modeh-ani',
    nameHebrew: 'מוֹדֶה אֲנִי',
    nameEnglish: 'Modeh Ani',
    category: 'morning',
    sortOrder: 1,
    whenSaid: 'First thing upon waking, before getting out of bed',
    whySaid: 'We thank Hashem for returning our soul — for the gift of another day of life.',
    inspirationText: 'Every morning is a gift. Before your feet touch the ground, before you check your phone, before anything — you say "thank you." This prayer is your first conversation with God each day.',
    requiredLevel: 1,
    estimatedReadSeconds: 15,
    sections: [
      {
        id: 'modeh-ani-1',
        sortOrder: 1,
        hebrewText: 'מוֹדֶה אֲנִי לְפָנֶיךָ',
        transliteration: 'Modeh ani l\'fanecha',
        translation: 'I give thanks before You',
        notes: 'מוֹדֶה = I give thanks. אֲנִי = I. לְפָנֶיךָ = before You.',
      },
      {
        id: 'modeh-ani-2',
        sortOrder: 2,
        hebrewText: 'מֶלֶךְ חַי וְקַיָּם',
        transliteration: 'Melech chai v\'kayam',
        translation: 'Living and eternal King',
        notes: 'מֶלֶךְ = King. חַי = living. וְקַיָּם = and enduring/eternal.',
      },
      {
        id: 'modeh-ani-3',
        sortOrder: 3,
        hebrewText: 'שֶׁהֶחֱזַרְתָּ בִּי נִשְׁמָתִי',
        transliteration: 'She\'hechezarta bi nishmati',
        translation: 'For You have returned my soul within me',
        notes: 'שֶׁהֶחֱזַרְתָּ = that You returned. בִּי = within me. נִשְׁמָתִי = my soul.',
      },
      {
        id: 'modeh-ani-4',
        sortOrder: 4,
        hebrewText: 'בְּחֶמְלָה רַבָּה אֱמוּנָתֶךָ',
        transliteration: 'B\'chemla raba emunatecha',
        translation: 'With compassion — great is Your faithfulness',
        notes: 'בְּחֶמְלָה = with compassion. רַבָּה = great/abundant. אֱמוּנָתֶךָ = Your faithfulness.',
      },
    ],
  },
  {
    id: 'hamotzi',
    slug: 'hamotzi',
    nameHebrew: 'הַמּוֹצִיא',
    nameEnglish: 'Hamotzi',
    category: 'brachot',
    sortOrder: 2,
    whenSaid: 'Before eating bread',
    whySaid: 'We acknowledge that everything we have — even our daily bread — comes from Hashem.',
    inspirationText: 'Before you take that first bite, pause. Recognize that this food traveled an incredible journey to reach your table — and behind it all is God\'s kindness.',
    requiredLevel: 2,
    estimatedReadSeconds: 8,
    sections: [
      {
        id: 'hamotzi-1',
        sortOrder: 1,
        hebrewText: 'בָּרוּךְ אַתָּה ה׳ אֱלֹקֵינוּ מֶלֶךְ הָעוֹלָם',
        transliteration: 'Baruch Atah Adonai Elokeinu Melech ha\'olam',
        translation: 'Blessed are You, Lord our God, King of the universe',
        notes: 'This is the standard bracha formula. You\'ll see it in almost every blessing!',
      },
      {
        id: 'hamotzi-2',
        sortOrder: 2,
        hebrewText: 'הַמּוֹצִיא לֶחֶם מִן הָאָרֶץ',
        transliteration: 'Hamotzi lechem min ha\'aretz',
        translation: 'Who brings forth bread from the earth',
        notes: 'הַמּוֹצִיא = Who brings forth. לֶחֶם = bread. מִן הָאָרֶץ = from the earth.',
      },
    ],
  },
  {
    id: 'shema',
    slug: 'shema',
    nameHebrew: 'שְׁמַע יִשְׂרָאֵל',
    nameEnglish: 'Shema',
    category: 'shema',
    sortOrder: 3,
    whenSaid: 'Morning and evening prayers, and before going to sleep',
    whySaid: 'The declaration of God\'s unity — the most fundamental statement of Jewish faith. Jews have said these words for over 3,000 years.',
    inspirationText: 'These six words are the heart of Judaism. They\'re the first words a Jewish child learns, the last words said before death, and every morning and evening in between. When you say Shema, you join a chain going back to Abraham.',
    requiredLevel: 3,
    estimatedReadSeconds: 60,
    sections: [
      {
        id: 'shema-1',
        sortOrder: 1,
        hebrewText: 'שְׁמַע יִשְׂרָאֵל ה׳ אֱלֹקֵינוּ ה׳ אֶחָד',
        transliteration: 'Shma Yisrael, Adonai Elokeinu, Adonai Echad',
        translation: 'Hear O Israel, the Lord is our God, the Lord is One',
        notes: 'שְׁמַע = Hear/Listen. יִשְׂרָאֵל = Israel (all of us). אֶחָד = One.',
      },
      {
        id: 'shema-2',
        sortOrder: 2,
        hebrewText: 'בָּרוּךְ שֵׁם כְּבוֹד מַלְכוּתוֹ לְעוֹלָם וָעֶד',
        transliteration: 'Baruch shem k\'vod malchuto l\'olam va\'ed',
        translation: 'Blessed is the Name of His glorious kingdom forever and ever',
        notes: 'This line is said quietly (except on Yom Kippur). It\'s a response to the declaration of God\'s unity.',
      },
      {
        id: 'shema-3',
        sortOrder: 3,
        hebrewText: 'וְאָהַבְתָּ אֵת ה׳ אֱלֹקֶיךָ',
        transliteration: 'V\'ahavta et Adonai Elokecha',
        translation: 'And you shall love the Lord your God',
        notes: 'וְאָהַבְתָּ = And you shall love. This begins the first paragraph of the Shema.',
      },
      {
        id: 'shema-4',
        sortOrder: 4,
        hebrewText: 'בְּכָל לְבָבְךָ וּבְכָל נַפְשְׁךָ וּבְכָל מְאֹדֶךָ',
        transliteration: 'B\'chol l\'vav\'cha uv\'chol nafsh\'cha uv\'chol m\'odecha',
        translation: 'With all your heart, with all your soul, and with all your might',
        notes: 'לְבָבְךָ = your heart. נַפְשְׁךָ = your soul. מְאֹדֶךָ = your might/resources.',
      },
      {
        id: 'shema-5',
        sortOrder: 5,
        hebrewText: 'וְהָיוּ הַדְּבָרִים הָאֵלֶּה אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם עַל לְבָבֶךָ',
        transliteration: 'V\'hayu had\'varim ha\'eileh asher anochi m\'tzav\'cha hayom al l\'vavecha',
        translation: 'And these words which I command you today shall be upon your heart',
        notes: 'הַדְּבָרִים = the words/things. הַיּוֹם = today (every day feels like the first time).',
      },
      {
        id: 'shema-6',
        sortOrder: 6,
        hebrewText: 'וְשִׁנַּנְתָּם לְבָנֶיךָ וְדִבַּרְתָּ בָּם',
        transliteration: 'V\'shinantam l\'vanecha v\'dibarta bam',
        translation: 'And you shall teach them to your children, and speak of them',
        notes: 'וְשִׁנַּנְתָּם = and you shall teach (sharpen). לְבָנֶיךָ = to your children.',
      },
      {
        id: 'shema-7',
        sortOrder: 7,
        hebrewText: 'בְּשִׁבְתְּךָ בְּבֵיתֶךָ וּבְלֶכְתְּךָ בַדֶּרֶךְ',
        transliteration: 'B\'shiv\'t\'cha b\'veitecha uv\'lecht\'cha vaderech',
        translation: 'When you sit in your house, and when you walk on the way',
        notes: 'בְּבֵיתֶךָ = in your house. בַדֶּרֶךְ = on the road/way.',
      },
      {
        id: 'shema-8',
        sortOrder: 8,
        hebrewText: 'וּבְשָׁכְבְּךָ וּבְקוּמֶךָ',
        transliteration: 'Uv\'shoch\'b\'cha uv\'kumecha',
        translation: 'When you lie down and when you rise up',
        notes: 'This is why we say Shema morning and evening — "when you lie down and when you rise up."',
      },
    ],
  },
  {
    id: 'shehakol',
    slug: 'shehakol',
    nameHebrew: 'שֶׁהַכֹּל',
    nameEnglish: 'Shehakol',
    category: 'brachot',
    sortOrder: 4,
    whenSaid: 'Before eating/drinking items like water, meat, eggs, candy, juice',
    whySaid: 'We recognize that everything in the world came into being through God\'s word.',
    inspirationText: 'This blessing covers almost everything — water, juice, meat, candy, eggs. When in doubt about which bracha to say, Shehakol has you covered.',
    requiredLevel: 2,
    estimatedReadSeconds: 8,
    sections: [
      {
        id: 'shehakol-1',
        sortOrder: 1,
        hebrewText: 'בָּרוּךְ אַתָּה ה׳ אֱלֹקֵינוּ מֶלֶךְ הָעוֹלָם',
        transliteration: 'Baruch Atah Adonai Elokeinu Melech ha\'olam',
        translation: 'Blessed are You, Lord our God, King of the universe',
      },
      {
        id: 'shehakol-2',
        sortOrder: 2,
        hebrewText: 'שֶׁהַכֹּל נִהְיָה בִּדְבָרוֹ',
        transliteration: 'Shehakol nihyah bidvaro',
        translation: 'That everything came to be through His word',
        notes: 'שֶׁהַכֹּל = that everything. נִהְיָה = came to be. בִּדְבָרוֹ = through His word.',
      },
    ],
  },
  {
    id: 'ha-eitz',
    slug: 'ha-eitz',
    nameHebrew: 'בּוֹרֵא פְּרִי הָעֵץ',
    nameEnglish: 'Borei Pri Ha\'Eitz',
    category: 'brachot',
    sortOrder: 5,
    whenSaid: 'Before eating fruit that grows on trees (apples, oranges, grapes, etc.)',
    whySaid: 'We thank Hashem for creating the fruit of the tree.',
    inspirationText: 'Next time you bite into an apple, pause and say these words. You\'re acknowledging the incredible process — from seed to tree to fruit to your hand.',
    requiredLevel: 2,
    estimatedReadSeconds: 8,
    sections: [
      {
        id: 'ha-eitz-1',
        sortOrder: 1,
        hebrewText: 'בָּרוּךְ אַתָּה ה׳ אֱלֹקֵינוּ מֶלֶךְ הָעוֹלָם',
        transliteration: 'Baruch Atah Adonai Elokeinu Melech ha\'olam',
        translation: 'Blessed are You, Lord our God, King of the universe',
      },
      {
        id: 'ha-eitz-2',
        sortOrder: 2,
        hebrewText: 'בּוֹרֵא פְּרִי הָעֵץ',
        transliteration: 'Borei pri ha\'eitz',
        translation: 'Who creates the fruit of the tree',
        notes: 'בּוֹרֵא = Who creates. פְּרִי = fruit. הָעֵץ = the tree.',
      },
    ],
  },
  {
    id: 'ha-adamah',
    slug: 'ha-adamah',
    nameHebrew: 'בּוֹרֵא פְּרִי הָאֲדָמָה',
    nameEnglish: 'Borei Pri Ha\'Adamah',
    category: 'brachot',
    sortOrder: 6,
    whenSaid: 'Before eating vegetables and produce that grows from the ground',
    whySaid: 'We thank Hashem for creating the fruit of the earth.',
    inspirationText: 'Carrots, potatoes, tomatoes, lettuce — everything that grows from the ground gets this bracha.',
    requiredLevel: 2,
    estimatedReadSeconds: 8,
    sections: [
      {
        id: 'ha-adamah-1',
        sortOrder: 1,
        hebrewText: 'בָּרוּךְ אַתָּה ה׳ אֱלֹקֵינוּ מֶלֶךְ הָעוֹלָם',
        transliteration: 'Baruch Atah Adonai Elokeinu Melech ha\'olam',
        translation: 'Blessed are You, Lord our God, King of the universe',
      },
      {
        id: 'ha-adamah-2',
        sortOrder: 2,
        hebrewText: 'בּוֹרֵא פְּרִי הָאֲדָמָה',
        transliteration: 'Borei pri ha\'adamah',
        translation: 'Who creates the fruit of the earth',
        notes: 'הָאֲדָמָה = the earth/ground. Same formula as Ha\'Eitz but for ground-growing produce.',
      },
    ],
  },
];

export function getPrayerBySlug(slug: string): Prayer | undefined {
  return PRAYERS.find(p => p.slug === slug);
}

export function getPrayersByCategory(category: string): Prayer[] {
  return PRAYERS.filter(p => p.category === category);
}
