import type { DaveningService } from '@/types';

export const WEEKDAY_SHACHARIT: DaveningService = {
  id: 'weekday-shacharit',
  name: 'Weekday Shacharit',
  nameHebrew: 'שַׁחֲרִית חוֹל',
  type: 'weekday',
  timeOfDay: 'shacharit',
  description: 'The complete weekday morning prayer service',
  estimatedMinutes: 35,
  segments: [
    // =========================================================================
    // SEGMENT 1: Birkot HaShachar (Morning Blessings)
    // =========================================================================
    {
      id: 'birkot-hashachar',
      title: 'Birkot HaShachar',
      titleHebrew: 'בִּרְכוֹת הַשַּׁחַר',
      description: 'The morning blessings — thanking Hashem for the basics of life',
      color: '#D4A373',
      items: [
        {
          id: 'birkot-modeh-ani',
          prayerId: 'modeh-ani',
          type: 'prayer',
          label: 'Modeh Ani',
          labelHebrew: 'מוֹדֶה אֲנִי',
          amud: {
            role: 'silent_individual',
            instruction: 'Said immediately upon waking, before washing hands. Stay in bed or sit up.',
            notes: 'This is the very first thing said each morning — thanking Hashem for restoring your soul.',
          },
          estimatedSeconds: 15,
        },
        {
          id: 'birkot-netilat-yadayim',
          prayerId: 'netilat-yadayim',
          type: 'prayer',
          label: 'Netilat Yadayim',
          labelHebrew: 'נְטִילַת יָדַיִם',
          amud: {
            role: 'silent_individual',
            instruction: 'Pour water alternately on each hand three times, then say the blessing.',
            notes: 'Ritual hand-washing to start the day in purity. A cup and basin are used.',
          },
          estimatedSeconds: 30,
        },
        {
          id: 'birkot-asher-yatzar',
          prayerId: 'asher-yatzar',
          type: 'prayer',
          label: 'Asher Yatzar',
          labelHebrew: 'אֲשֶׁר יָצַר',
          amud: {
            role: 'silent_individual',
            instruction: 'Said after using the restroom. A blessing thanking Hashem for the body.',
            notes: 'This beautiful blessing thanks Hashem for the miraculous design of the human body.',
          },
          estimatedSeconds: 30,
        },
        {
          id: 'birkot-elokai-neshama',
          prayerId: 'elokai-neshama',
          type: 'prayer',
          label: 'Elokai Neshama',
          labelHebrew: 'אֱלֹקַי נְשָׁמָה',
          amud: {
            role: 'silent_individual',
            instruction: 'A prayer acknowledging that the soul Hashem gave you is pure.',
            notes: 'Recognizes that your soul is a gift from Hashem, returned each morning.',
          },
          estimatedSeconds: 30,
        },
        {
          id: 'birkot-birchos-hatorah',
          prayerId: 'birchos-hatorah',
          type: 'prayer',
          label: 'Birchos HaTorah',
          labelHebrew: 'בִּרְכוֹת הַתּוֹרָה',
          amud: {
            role: 'silent_individual',
            instruction: 'Blessings over Torah study. Must be said before learning any Torah.',
            notes: 'These blessings are required before studying Torah each day. Many follow them with short Torah passages.',
          },
          estimatedSeconds: 45,
        },
        {
          id: 'birkot-birchos-hashachar',
          prayerId: 'birchos-hashachar',
          type: 'prayer',
          label: 'Birchos HaShachar',
          labelHebrew: 'בִּרְכוֹת הַשַּׁחַר',
          amud: {
            role: 'silent_individual',
            instruction: 'A series of blessings thanking Hashem for daily gifts — sight, clothing, freedom, strength.',
            notes: 'Some communities say these aloud with the congregation responding Amen. Others say them individually.',
          },
          estimatedSeconds: 90,
        },
      ],
    },

    // =========================================================================
    // SEGMENT 2: Pesukei D'Zimra (Verses of Praise)
    // =========================================================================
    {
      id: 'pesukei-dzimra',
      title: "Pesukei D'Zimra",
      titleHebrew: 'פְּסוּקֵי דְזִמְרָא',
      description: 'Psalms and praises to prepare your heart for the main prayer',
      color: '#5FA8D3',
      items: [
        {
          id: 'pdzimra-hodu',
          prayerId: 'hodu',
          type: 'prayer',
          label: 'Hodu',
          labelHebrew: 'הוֹדוּ',
          amud: {
            role: 'both',
            instruction: 'The Shaliach Tzibbur leads and the congregation joins in responsive verses.',
            notes: 'A collection of verses giving thanks to Hashem. Sets the tone for the Pesukei D\'Zimra section.',
          },
          estimatedSeconds: 120,
        },
        {
          id: 'pdzimra-baruch-sheamar',
          prayerId: 'baruch-sheamar',
          type: 'prayer',
          label: "Baruch She'amar",
          labelHebrew: 'בָּרוּךְ שֶׁאָמַר',
          amud: {
            role: 'both',
            instruction: 'Stand for this opening blessing of Pesukei D\'Zimra.',
            physicalActions: ['stand'],
            notes: 'This blessing "opens" the Pesukei D\'Zimra section. Stand while reciting it. Hold the front two tzitzit during the blessing.',
          },
          estimatedSeconds: 60,
        },
        {
          id: 'pdzimra-mizmor-ltodah',
          prayerId: 'mizmor-ltodah',
          type: 'prayer',
          label: "Mizmor L'Todah",
          labelHebrew: 'מִזְמוֹר לְתוֹדָה',
          amud: {
            role: 'both',
            instruction: 'Psalm 100 — a psalm of thanksgiving. Said standing in some communities.',
            notes: 'A short but important psalm of gratitude. Omitted on Erev Pesach and Chol HaMoed Pesach.',
          },
          estimatedSeconds: 30,
        },
        {
          id: 'pdzimra-ashrei',
          prayerId: 'ashrei',
          type: 'prayer',
          label: 'Ashrei',
          labelHebrew: 'אַשְׁרֵי',
          amud: {
            role: 'both',
            instruction: 'Psalm 145 with introductory verses. One of the most important daily prayers.',
            notes: 'Said three times daily. The verses follow the Hebrew alphabet (aleph-bet). Focus on the meaning of each verse.',
          },
          estimatedSeconds: 90,
        },
        {
          id: 'pdzimra-az-yashir',
          prayerId: 'az-yashir',
          type: 'prayer',
          label: 'Az Yashir',
          labelHebrew: 'אָז יָשִׁיר',
          amud: {
            role: 'both',
            instruction: 'The Song of the Sea — Moshe and the Jewish people sang this after crossing the Red Sea.',
            notes: 'Some have the custom to stand. This is the song of triumph from Exodus 15.',
          },
          estimatedSeconds: 120,
        },
        {
          id: 'pdzimra-yishtabach',
          prayerId: 'yishtabach',
          type: 'prayer',
          label: 'Yishtabach',
          labelHebrew: 'יִשְׁתַּבַּח',
          amud: {
            role: 'both',
            instruction: 'Stand for this closing blessing of Pesukei D\'Zimra.',
            physicalActions: ['stand'],
            notes: 'This blessing "closes" the Pesukei D\'Zimra section. Stand while reciting it. Contains 15 expressions of praise.',
          },
          estimatedSeconds: 45,
        },
        {
          id: 'pdzimra-half-kaddish',
          prayerId: 'kaddish-half',
          type: 'kaddish',
          label: 'Half Kaddish',
          labelHebrew: 'חֲצִי קַדִּישׁ',
          amud: {
            role: 'shaliach_tzibbur',
            instruction: 'The Shaliach Tzibbur recites Half Kaddish. Congregation responds at the appropriate points.',
            congregationResponse: 'אָמֵן. יְהֵא שְׁמֵהּ רַבָּא...',
            congregationResponseTransliteration: 'Amen. Yehei shmei rabba...',
            physicalActions: ['stand'],
            waitForCongregation: true,
            notes: 'Half Kaddish marks the transition between sections of the service. Respond "Amen" and "Yehei shmei rabba mevarach..." with enthusiasm.',
          },
          estimatedSeconds: 45,
        },
      ],
    },

    // =========================================================================
    // SEGMENT 3: Shema & Brachot
    // =========================================================================
    {
      id: 'shema-brachot',
      title: 'Shema & Brachot',
      titleHebrew: 'שְׁמַע וּבִרְכוֹתֶיהָ',
      description: 'The core declaration of faith and its surrounding blessings',
      color: '#7C3AED',
      items: [
        {
          id: 'shema-barchu',
          prayerId: 'barchu',
          type: 'responsive',
          label: 'Barchu',
          labelHebrew: 'בָּרְכוּ',
          amud: {
            role: 'both',
            instruction: 'The Shaliach Tzibbur calls the congregation to prayer. Everyone bows at "Barchu" and stands upright at Hashem\'s name.',
            congregationResponse: 'בָּרוּךְ ה׳ הַמְבוֹרָךְ לְעוֹלָם וָעֶד',
            congregationResponseTransliteration: "Baruch Hashem ham'vorach l'olam va'ed",
            physicalActions: ['bow_and_stand'],
            waitForCongregation: true,
            notes: 'The official "call to prayer." Bow when saying "Barchu" and straighten up when saying Hashem\'s name. This marks the start of the Shema section.',
          },
          estimatedSeconds: 20,
        },
        {
          id: 'shema-yotzer-or',
          prayerId: 'yotzer-or',
          type: 'prayer',
          label: 'Yotzer Or',
          labelHebrew: 'יוֹצֵר אוֹר',
          amud: {
            role: 'shaliach_tzibbur',
            instruction: 'The first blessing before Shema — praising Hashem as Creator of light.',
            notes: 'This blessing acknowledges Hashem as the Creator who renews creation daily. Contains the Kedusha D\'Yotzer (a mini-Kedusha).',
          },
          estimatedSeconds: 120,
        },
        {
          id: 'shema-ahavah-rabbah',
          prayerId: 'ahavah-rabbah',
          type: 'prayer',
          label: 'Ahavah Rabbah',
          labelHebrew: 'אַהֲבָה רַבָּה',
          amud: {
            role: 'shaliach_tzibbur',
            instruction: 'The second blessing before Shema — thanking Hashem for His love and the gift of Torah.',
            notes: 'Expresses gratitude for Hashem\'s deep love, manifested through giving us the Torah. Leads directly into the Shema.',
          },
          estimatedSeconds: 90,
        },
        {
          id: 'shema-shema',
          prayerId: 'shema',
          type: 'prayer',
          label: 'Shema',
          labelHebrew: 'שְׁמַע',
          amud: {
            role: 'both',
            instruction: 'Cover your eyes with your right hand for the first verse. Concentrate deeply on accepting Hashem\'s sovereignty.',
            physicalActions: ['cover_eyes'],
            notes: 'The central declaration of Jewish faith: "Hear O Israel, Hashem is our God, Hashem is One." Cover your eyes to focus completely. The three paragraphs discuss love of Hashem, reward and consequence, and the mitzvah of tzitzit.',
          },
          estimatedSeconds: 180,
        },
        {
          id: 'shema-emet-vyatziv',
          prayerId: 'emet-vyatziv',
          type: 'prayer',
          label: "Emet V'Yatziv",
          labelHebrew: 'אֶמֶת וְיַצִּיב',
          amud: {
            role: 'shaliach_tzibbur',
            instruction: 'The blessing after Shema. Leads directly into the Amidah — do not interrupt between the final words "Ga\'al Yisrael" and the start of the Amidah.',
            notes: 'Affirms the truth of everything declared in the Shema. Ends with the blessing of redemption. Important: go straight from the end of this blessing into the Amidah without pause (this is called "semichat geulah l\'tefillah").',
          },
          estimatedSeconds: 90,
        },
      ],
    },

    // =========================================================================
    // SEGMENT 4: Amidah (Standing Prayer)
    // =========================================================================
    {
      id: 'amidah',
      title: 'Amidah',
      titleHebrew: 'עֲמִידָה',
      description: 'The central prayer — 19 blessings said standing, facing Jerusalem',
      color: '#1B4965',
      items: [
        {
          id: 'amidah-silent-instruction',
          type: 'instruction',
          label: 'Silent Amidah',
          amud: {
            role: 'silent_individual',
            instruction: 'Everyone prays the Amidah silently. Take three steps forward before beginning. Stand with feet together, facing Jerusalem.',
            physicalActions: ['three_steps_forward', 'stand'],
            notes: 'The Amidah is the most important prayer of the service. Stand with your feet together as if standing before a king. Face east (toward Jerusalem). Keep your voice to a whisper — only you should hear the words.',
          },
          estimatedSeconds: 15,
        },
        {
          id: 'amidah-shemoneh-esrei',
          prayerId: 'shemoneh-esrei',
          type: 'prayer',
          label: 'Shemoneh Esrei',
          labelHebrew: 'שְׁמוֹנֶה עֶשְׂרֵה',
          amud: {
            role: 'silent_individual',
            instruction: 'Recite all 19 blessings silently. Bow at the designated points. At the end, take three steps back, bow left, right, and center.',
            physicalActions: ['stand', 'three_steps_forward'],
            notes: 'The "18 blessings" (actually 19). The first three blessings praise Hashem, the middle 13 are requests, and the last three give thanks. Bow at the beginning and end of the first blessing and at Modim. Take three steps back at the end.',
          },
          estimatedSeconds: 300,
        },
        {
          id: 'amidah-chazarat-hashatz-instruction',
          type: 'instruction',
          label: 'Chazarat HaShatz',
          labelHebrew: 'חֲזָרַת הַשַּׁ״ץ',
          amud: {
            role: 'shaliach_tzibbur',
            instruction: 'The Shaliach Tzibbur repeats the Amidah aloud. The congregation listens and responds "Amen" after each blessing.',
            waitForCongregation: true,
            notes: 'The repetition ensures that anyone who could not pray on their own fulfills their obligation. Listen carefully and answer "Amen" to each blessing. The Kedusha is added during the repetition.',
          },
          estimatedSeconds: 15,
        },
        {
          id: 'amidah-kedusha',
          prayerId: 'kedusha-shacharit',
          type: 'responsive',
          label: 'Kedusha',
          labelHebrew: 'קְדוּשָּׁה',
          amud: {
            role: 'both',
            instruction: 'Stand with feet together. Rise on your toes three times at "Kadosh, Kadosh, Kadosh." The congregation recites the responsive portions together.',
            congregationResponse: 'קָדוֹשׁ קָדוֹשׁ קָדוֹשׁ ה׳ צְבָאוֹת מְלֹא כָל הָאָרֶץ כְּבוֹדוֹ',
            congregationResponseTransliteration: "Kadosh Kadosh Kadosh Hashem Tzva'ot, m'lo chol ha'aretz k'vodo",
            physicalActions: ['stand', 'rise_on_toes'],
            waitForCongregation: true,
            notes: 'One of the holiest moments in the service. We emulate the angels declaring Hashem\'s holiness. Rise on your toes at each "Kadosh." Must be said with a minyan (quorum of 10).',
          },
          estimatedSeconds: 90,
        },
        {
          id: 'amidah-modim-derabanan',
          prayerId: 'modim-derabanan',
          type: 'prayer',
          label: "Modim D'Rabbanan",
          labelHebrew: 'מוֹדִים דְּרַבָּנָן',
          amud: {
            role: 'congregation',
            instruction: 'When the Shaliach Tzibbur reaches Modim in the repetition, the congregation bows and recites this special version of thanksgiving quietly.',
            physicalActions: ['bow'],
            notes: 'While the Shaliach Tzibbur says the regular Modim, the congregation says this rabbinical version. Bow when you begin saying it. This ensures everyone personally gives thanks rather than just listening.',
          },
          estimatedSeconds: 30,
        },
      ],
    },

    // =========================================================================
    // SEGMENT 5: Post-Amidah
    // =========================================================================
    {
      id: 'post-amidah',
      title: 'Post-Amidah',
      titleHebrew: 'סִיּוּם הַתְּפִלָּה',
      description: 'Closing prayers after the Amidah',
      color: '#4A7C59',
      items: [
        {
          id: 'post-tachanun',
          prayerId: 'tachanun',
          type: 'prayer',
          label: 'Tachanun',
          labelHebrew: 'תַּחֲנוּן',
          amud: {
            role: 'silent_individual',
            instruction: 'Supplication prayer. Rest your head on your arm (left arm if wearing tefillin on the left, right arm otherwise).',
            physicalActions: ['sit'],
            notes: 'Tachanun is a humble plea for mercy. Not said on Shabbat, holidays, Rosh Chodesh, and certain other joyful days. On Mondays and Thursdays a longer version is added. Check the calendar if unsure.',
          },
          estimatedSeconds: 120,
        },
        {
          id: 'post-half-kaddish',
          prayerId: 'kaddish-half',
          type: 'kaddish',
          label: 'Half Kaddish',
          labelHebrew: 'חֲצִי קַדִּישׁ',
          amud: {
            role: 'shaliach_tzibbur',
            instruction: 'The Shaliach Tzibbur recites Half Kaddish to mark the transition to the closing section.',
            congregationResponse: 'אָמֵן. יְהֵא שְׁמֵהּ רַבָּא...',
            congregationResponseTransliteration: 'Amen. Yehei shmei rabba...',
            physicalActions: ['stand'],
            waitForCongregation: true,
            notes: 'Respond with "Amen" and "Yehei shmei rabba mevarach l\'alam u\'l\'almei almaya" with concentration.',
          },
          estimatedSeconds: 45,
        },
        {
          id: 'post-ashrei',
          prayerId: 'ashrei',
          type: 'prayer',
          label: 'Ashrei',
          labelHebrew: 'אַשְׁרֵי',
          amud: {
            role: 'both',
            instruction: 'Ashrei is recited a second time here. Sit for this recitation.',
            physicalActions: ['sit'],
            notes: 'This is the second of three daily recitations of Ashrei (Psalm 145). Our Sages taught that one who says Ashrei three times daily is assured a place in the World to Come.',
          },
          estimatedSeconds: 90,
        },
        {
          id: 'post-uva-ltzion',
          prayerId: 'uva-ltzion',
          type: 'prayer',
          label: "U'Va L'Tzion",
          labelHebrew: 'וּבָא לְצִיּוֹן',
          amud: {
            role: 'both',
            instruction: 'A prayer declaring that a redeemer will come to Zion. Includes the Kedusha D\'Sidra.',
            notes: 'Contains Aramaic translations of key verses. The "Kedusha D\'Sidra" within this prayer was instituted so that every Jew would study a bit of Torah daily, even through the prayer service.',
          },
          estimatedSeconds: 120,
        },
        {
          id: 'post-full-kaddish',
          prayerId: 'kaddish-full',
          type: 'kaddish',
          label: 'Full Kaddish',
          labelHebrew: 'קַדִּישׁ שָׁלֵם',
          amud: {
            role: 'shaliach_tzibbur',
            instruction: 'The Shaliach Tzibbur recites the Full Kaddish (Kaddish Titkabel), which includes the prayer that our prayers be accepted.',
            congregationResponse: 'אָמֵן',
            congregationResponseTransliteration: 'Amen',
            physicalActions: ['stand'],
            waitForCongregation: true,
            notes: 'The Full Kaddish adds the paragraph "Titkabel" — a prayer that all of our prayers be received favorably. This signifies the formal conclusion of the main service.',
          },
          estimatedSeconds: 60,
        },
        {
          id: 'post-aleinu',
          prayerId: 'aleinu',
          type: 'prayer',
          label: 'Aleinu',
          labelHebrew: 'עָלֵינוּ',
          amud: {
            role: 'both',
            instruction: 'Stand and bow at "Va\'anachnu kor\'im u\'mishtachavim" — we bow and prostrate before the King of Kings.',
            physicalActions: ['stand', 'bow'],
            notes: 'Aleinu declares Hashem\'s sovereignty over all creation. Bow deeply (some bend their knees and bow) at the designated phrase. This was originally composed by Joshua upon entering the Land of Israel.',
          },
          estimatedSeconds: 60,
        },
        {
          id: 'post-mourners-kaddish',
          prayerId: 'kaddish-mourners',
          type: 'kaddish',
          label: "Mourner's Kaddish",
          labelHebrew: 'קַדִּישׁ יָתוֹם',
          amud: {
            role: 'both',
            instruction: 'Mourners recite the Kaddish. The congregation responds "Amen" and "Yehei shmei rabba..." at the appropriate points.',
            congregationResponse: 'אָמֵן. יְהֵא שְׁמֵהּ רַבָּא...',
            congregationResponseTransliteration: 'Amen. Yehei shmei rabba...',
            physicalActions: ['stand'],
            waitForCongregation: true,
            notes: 'Recited by mourners (those within the first year after losing a parent, or during the annual yahrtzeit). Even if you are not a mourner, respond "Amen" — it is a great merit for the departed souls.',
          },
          estimatedSeconds: 45,
        },
      ],
    },
  ],
};
